### Libraries

In [1]:
import pandas as pd

### Exercicio 1

1) Quais os serviços prestados pela Telco
2) Qual o serviço mais rentável em média?
3) Qual o perfil de carteira de serviços mais rentáveis?
4) Mapeie as características demográficas dos clientes mais rentáveis.
5) Quanto aos clientes mais antigos (em média) quais características demográficas deles?
6) Faça a analise univariada das colunas de serviço pra analisar os missings.

In [2]:
##https://www.kaggle.com/datasets/blastchar/telco-customer-churn
telco = pd.read_csv("./data/telco.csv",parse_dates=True)
telco.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

### Exercicio 2

1) Qual a duração média das viagens?
2) Qual media do numero de passageiros?
3) As pessoas que pegam taxi se movem mais para norte ou para o sul? Para leste ou pra oeste?
4) Classifique as viagens entre curta, media e longa. Faça critérios usando latitude e longitude e tempo.
5) Liste top viagens mais curtas com o criterio latitude e que gastaram mais tempo.
6) Liste top viagens mais longas com o criterior tempo e que tiveram a menor distancia entre latitude e longitude.

In [9]:
#https://www.kaggle.com/datasets/yasserh/nyc-taxi-trip-duration
nyc = pd.read_csv("./data/NYC.csv",parse_dates=True)
nyc.head()

,id,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration
0,id2875421,2,2016-03-14 17:24:55,2016-03-14 17:32:30,1,-73.982155,40.767937,-73.964630,40.765602,N,455
1,id2377394,1,2016-06-12 00:43:35,2016-06-12 00:54:38,1,-73.980415,40.738564,-73.999481,40.731152,N,663
2,id3858529,2,2016-01-19 11:35:24,2016-01-19 12:10:48,1,-73.979027,40.763939,-74.005333,40.710087,N,2124
3,id3504673,2,2016-04-06 19:32:31,2016-04-06 19:39:40,1,-74.010040,40.719971,-74.012268,40.706718,N,429
4,id2181028,2,2016-03-26 13:30:55,2016-03-26 13:38:10,1,-73.973053,40.793209,-73.972923,40.782520,N,435