## 1. Primeiros passos (titanic)

Nesessário instalar bilbiotecas. Pode ser feito por aqui usando "!pip" ou usando terminal. Abaixo como instalar pandas.

In [6]:
# !pip install pandas

Uma vez instalada a biblioteca, é necessário importá-la para o ambiente de trabalho. O nome da biblioteca é "pandas" e a forma mais comum de a importar é usando o alias "pd". O alias é uma forma abreviada de se referir à biblioteca, facilitando a escrita do código.

In [7]:
import pandas as pd

## 2. Importando dados

Inicialmente, vamos importar um dataset conhecido, o "titanic". Este dataset contém informações sobre os passageiros do navio Titanic, incluindo se eles sobreviveram ou não, sua classe de cabine, idade, sexo, entre outros dados.

In [8]:
#dataset source
path = "../../00_Datasets/titanic.csv"

#read dataframe
ds = pd.read_csv(path)

#show first 10 rows
ds.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [9]:
#show last 10 rows
ds.tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

Descreva o que é cada linha e cada coluna. Faça um report sobre o seu entedimento.

Após analise do dataset acima quais incompatibilidades ou problemas de qualidade de dados voce identificou? Quais colunas tem valores faltantes? Quais colunas tem valores inconsistentes? Quais colunas tem valores duplicados? Quais colunas tem valores fora do intervalo esperado?

Uma maneira inteligente de fazer isso é talvez fazer uma coluna sumária que analise cada coluna e sua completude, consistência, duplicidade e validade. Portanto crie uma tabela sumária sobre com as colunas descritas abaixo:

In [10]:
#nome da coluna
#tipo de dados
#quantidade de valores únicos
#quantidade de valores faltantes
#quantidade de valores duplicados
#quantidade de dados inteiros
#quantidade de dados float
#quantidade de dados string
#quantidade de dados booleanos
#quantidade de dados nulos

#criando a tabela
summary = pd.DataFrame({
    'Column': ds.columns,
    'DataType': ds.dtypes,
    'UniqueValues': ds.nunique(),
    'MissingValues': ds.isnull().sum(),
    'DuplicatedValues': ds.apply(lambda x: x.duplicated().sum()),
    'IntegerValues': ds.apply(lambda x: x.apply(lambda y: isinstance(y, int)).sum()),
    'FloatValues': ds.apply(lambda x: x.apply(lambda y: isinstance(y, float)).sum()),
    'StringValues': ds.apply(lambda x: x.apply(lambda y: isinstance(y, str)).sum()),
    'BooleanValues': ds.apply(lambda x: x.apply(lambda y: isinstance(y, bool)).sum()),
})

summary

,Column,DataType,UniqueValues,MissingValues,DuplicatedValues,IntegerValues,FloatValues,StringValues,BooleanValues
PassengerId,PassengerId,int64,891,0,0,891,0,0,0
Survived,Survived,int64,2,0,889,891,0,0,0
Pclass,Pclass,int64,3,0,888,891,0,0,0
Name,Name,str,891,0,0,0,0,891,0
Sex,Sex,str,2,0,889,0,0,891,0
Age,Age,float64,88,177,802,0,891,0,0
SibSp,SibSp,int64,7,0,884,891,0,0,0
Parch,Parch,int64,7,0,884,891,0,0,0
Ticket,Ticket,str,681,0,210,0,0,891,0
Fare,Fare,float64,248,0,643,0,891,0,0
Cabin,Cabin,str,147,687,743,0,687,204,0
Embarked,Embarked,str,3,2,887,0,2,889,0

In [11]:
#duplicated values in columns "PassengerId" and "Name"
print("Valores duplicados na coluna 'PassengerId':")
print(ds['PassengerId'].duplicated().sum())
print("Valores duplicados na coluna 'Name':")
print(ds['Name'].duplicated().sum())

Valores duplicados na coluna 'PassengerId':
0
Valores duplicados na coluna 'Name':
0

In [12]:
#qual o padrao dos valores de ticket?
print("Valores únicos na coluna 'Ticket':")
print(ds['Ticket'].unique())

Valores únicos na coluna 'Ticket':
<StringArray>
[       'A/5 21171',         'PC 17599', 'STON/O2. 3101282',
           '113803',           '373450',           '330877',
            '17463',           '349909',           '347742',
           '237736',
 ...
           '349212',           '349217',           '349257',
             '7552', 'C.A./SOTON 34068',  'SOTON/OQ 392076',
           '211536',           '112053',           '111369',
           '370376']
Length: 681, dtype: str

In [13]:
#valores unicos dos tickets primeira classe
print("Valores únicos na coluna 'Ticket' para passageiros da primeira classe:")
print(ds[ds['Pclass'] == 1]['Ticket'].unique())

Valores únicos na coluna 'Ticket' para passageiros da primeira classe:
<StringArray>
['PC 17599',   '113803',    '17463',   '113783',   '113788',    '19950',
 'PC 17601', 'PC 17569', 'PC 17604',   '113789',
 ...
    '19972', 'PC 17756',    '11774', 'PC 17592',   '113055',    '17466',
 'PC 17590',      '695',   '112053',   '111369']
Length: 147, dtype: str

In [14]:
#ha valores duplicados de ticket ?
print("Valores duplicados na coluna 'Ticket':")
print(ds['Ticket'].duplicated().sum())

Valores duplicados na coluna 'Ticket':
210

In [15]:
#print as rows with duplicated tickets
print("Linhas com valores duplicados na coluna 'Ticket':")
print(ds[ds['Ticket'].duplicated(keep=False)])

Linhas com valores duplicados na coluna 'Ticket':
     PassengerId  Survived  Pclass  \
3              4         1       1
7              8         0       3
8              9         1       3
9             10         1       2
10            11         1       3
..           ...       ...     ...
876          877         0       3
879          880         1       1
880          881         1       2
885          886         0       3
888          889         0       3

                                                  Name     Sex   Age  SibSp  \
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
7                       Palsson, Master. Gosta Leonard    male   2.0      3
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1
..                                                 ...     ...   ...    ...
876                      Gustafsson, Mr. Alfred Ossian    male  20.0      0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1

     Parch      Ticket     Fare Cabin Embarked
3        0      113803  53.1000  C123        S
7        1      349909  21.0750   NaN        S
8        2      347742  11.1333   NaN        S
9        0      237736  30.0708   NaN        C
10       1     PP 9549  16.7000    G6        S
..     ...         ...      ...   ...      ...
876      0        7534   9.8458   NaN        S
879      1       11767  83.1583   C50        C
880      1      230433  26.0000   NaN        S
885      5      382652  29.1250   NaN        Q
888      2  W./C. 6607  23.4500   NaN        S

[344 rows x 12 columns]

In [16]:
#perguntas sobre a consistencia dos dados que valem ser feitas:
#- Qual é o formato dos valores na coluna "Ticket"? Eles seguem um padrão específico?
#- Existem valores duplicados na coluna "Ticket"? Se sim, isso pode indicar que diferentes passageiros compartilham o mesmo número de ticket, o que pode ser consistente com a realidade, mas também pode indicar um problema de qualidade de dados.
#- Existem valores faltantes na coluna "Ticket"? Se sim, isso pode indicar que algumas informações sobre os passageiros estão incompletas.
#- Existem valores inconsistentes na coluna "Ticket"? Por exemplo, valores que não seguem o formato esperado ou que contêm caracteres inesperados.

In [17]:
#quantas cabines diferentes existem no dataset?
print("Número de cabines diferentes no dataset:")
print(ds['Cabin'].nunique())

# https://titanicfacts.net/titanic-ship/#:~:text=There%20were%20840%20staterooms%20in%20all%2C%20416,–%20the%20top%20speed%20of%20the%20Titanic.
#o navio tinha 840 cabines, mas o dataset tem apenas 147 cabines diferentes, o que indica que muitos passageiros compartilham a mesma cabine ou que há informações faltantes sobre as cabines.

Número de cabines diferentes no dataset:
147

In [18]:
#idade em float ou int?
print("Tipo de dados na coluna 'Age':")
print(ds['Age'].dtype)

#idade em float, o que é consistente com a realidade, pois a idade pode ser expressa em anos e meses (por exemplo, 2.5 anos para um bebê de 2 anos e 6 meses). No entanto, isso também pode indicar que há valores faltantes ou inconsistentes na coluna "Age", como valores negativos ou valores muito altos que não são realistas para a idade humana.

Tipo de dados na coluna 'Age':
float64

In [19]:
#quantos passageiros existiam realmente a bordo do Titanic?
print("Número total de passageiros no dataset:")
print(len(ds))
#mas o número total de passageiros a bordo do Titanic era de aproximadamente 2.208, o que indica que o dataset pode não conter informações sobre todos os passageiros ou que há informações faltantes sobre alguns passageiros.
# https://pt.wikipedia.org/wiki/Naufrágio_do_RMS_Titanic

Número total de passageiros no dataset:
891

Com o seu conhecimento da historia do Titanic, quais hipoteses emergem a partir da sua exploracao dos dados? Quais perguntas voce gostaria de responder? Quais hipoteses voce gostaria de testar?

Se estiver sem ideias, tente responder as seguintes perguntas:
- Qual era a proporção de sobreviventes em relação ao total de passageiros?
- Qual era a proporção de sobreviventes por classe de cabine?
- Qual era a proporção de sobreviventes por sexo?
- Qual era a proporção de sobreviventes por faixa etária? `['0-12', '13-18', '19-35', '36-60', '60+']`
- Qual era a proporção de sobreviventes por número de irmãos/cônjuges a bordo?
- Qual era a proporção de sobreviventes por número de pais/filhos a bordo?

In [20]:
#Qual era a proporção de sobreviventes em relação ao total de passageiros?
total_passengers = len(ds)
survivors = ds['Survived'].sum()
proportion_survivors = survivors / total_passengers
print(f"Proporção de sobreviventes: {proportion_survivors:.2%}")

Proporção de sobreviventes: 38.38%

In [21]:
#Qual era a proporção de sobreviventes por classe de cabine?
survivors_by_class = ds.groupby('Pclass')['Survived'].mean()
print("Proporção de sobreviventes por classe de cabine:")
print(survivors_by_class)

Proporção de sobreviventes por classe de cabine:
Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [22]:
#Qual era a proporção de sobreviventes por sexo?
survivors_by_sex = ds.groupby('Sex')['Survived'].mean()
print("Proporção de sobreviventes por sexo:")
print(survivors_by_sex)

Proporção de sobreviventes por sexo:
Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [23]:
#Qual era a proporção de sobreviventes por faixa etária?
# Criar faixas etárias
bins = [0, 12, 18, 35, 60, 100]
labels = ['0-12', '13-18', '19-35', '36-60', '60+']
ds['AgeGroup'] = pd.cut(ds['Age'], bins=bins, labels=labels)
survivors_by_age_group = ds.groupby('AgeGroup')['Survived'].mean()
print("Proporção de sobreviventes por faixa etária:")
print(survivors_by_age_group)

Proporção de sobreviventes por faixa etária:
AgeGroup
0-12     0.579710
13-18    0.428571
19-35    0.382682
36-60    0.400000
60+      0.227273
Name: Survived, dtype: float64

In [28]:
ds

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,AgeGroup
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,19-35
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,36-60
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,19-35
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,19-35
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,19-35
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,19-35
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,19-35
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,19-35
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,19-35

In [24]:
#A coluna "SibSp" indica o número de irmãos/cônjuges a bordo.
#A coluna "Parch" indica o número de pais/filhos a bordo.

#qual das duas colunas usar?
#Se quero analisar a proporção de sobreviventes por número de irmãos/cônjuges a bordo, devo usar a coluna "SibSp". Se quero analisar a proporção de sobreviventes por número de pais/filhos a bordo, devo usar a coluna "Parch".

In [25]:
#unique values in SibSp column
print("Valores únicos na coluna 'SibSp':")
print(ds['SibSp'].unique())

#portanto numero inteiro de irmãos/cônjuges a bordo, variando de 0 a 8.

Valores únicos na coluna 'SibSp':
[1 0 3 4 2 5 8]

In [26]:
# Qual era a proporção de sobreviventes por número de irmãos/cônjuges a bordo?
survivors_by_siblings = ds.groupby('SibSp')['Survived'].mean()
print("Proporção de sobreviventes por número de irmãos/cônjuges a bordo:")
print(survivors_by_siblings)

Proporção de sobreviventes por número de irmãos/cônjuges a bordo:
SibSp
0    0.345395
1    0.535885
2    0.464286
3    0.250000
4    0.166667
5    0.000000
8    0.000000
Name: Survived, dtype: float64

In [27]:
#Qual era a proporção de sobreviventes por número de pais/filhos a bordo?
survivors_by_parents = ds.groupby('Parch')['Survived'].mean()
print("Proporção de sobreviventes por número de pais/filhos a bordo:")
print(survivors_by_parents)

Proporção de sobreviventes por número de pais/filhos a bordo:
Parch
0    0.343658
1    0.550847
2    0.500000
3    0.600000
4    0.000000
5    0.200000
6    0.000000
Name: Survived, dtype: float64